import { Window } from "happy-dom";
import { strict as assert } from "node:assert";
const win = new Window({ url: 'http://localhost/' });
for (const key of ['window','document','navigator','HTMLElement','HTMLInputElement','HTMLSelectElement','Element','Node','Text','Event','MouseEvent','CustomEvent','getComputedStyle']) (globalThis as any)[key] = (win as any)[key];
(globalThis as any).window = win;
const requests: { url: string; body: any }[] = [];
(globalThis as any).fetch = async (url: string, init?: RequestInit) => {
  const body = JSON.parse(String(init?.body ?? '{}')); requests.push({ url, body });
  if (url.endsWith('/connections/test')) return Response.json({ database: 'postgres', user: 'postgres', serverVersion: '17', ms: 2 });
  if (url.endsWith('/connections')) return Response.json({ id: 'local', label: body.label, url: 'postgres://localhost/postgres', environment: body.environment, readOnly: body.readOnly });
  if (url.endsWith('/open')) return Response.json({ path: body.path });
  return Response.json({ error: 'unexpected request' }, { status: 500 });
};
const React = (await import('react')).default;
const { createRoot } = await import('react-dom/client');
const { flushSync } = await import('react-dom');
const { DatabaseOpenModal } = await import('../src/DatabaseOpenModal.tsx');
const container = document.createElement('div'); document.body.append(container);
const root = createRoot(container);
let opened: any;
flushSync(() => root.render(React.createElement(DatabaseOpenModal, { initial: 'postgres', onClose() {}, onOpen(source) { opened = source; } })));
const button = (text: string) => [...container.querySelectorAll('button')].find(b => b.textContent === text)!;
assert(container.querySelector('input[type=password]'));
assert.equal((container.querySelector('input[type=checkbox]') as HTMLInputElement).checked, true);
button('Test Connection').click(); await Bun.sleep(10);
assert(container.textContent?.includes('PostgreSQL 17'));
container.querySelector('form')!.dispatchEvent(new Event('submit', { bubbles: true, cancelable: true })); await Bun.sleep(10);
assert.equal(opened.readOnly, true);
assert(requests.some(r => r.url.endsWith('/connections') && r.body.url.includes('sslmode=prefer')));
flushSync(() => root.unmount());
console.log('PASS: connection test, secure credential fields, default read-only and save/open');
